baseurl = ""
languageCode = "en-gb"
title = "HPSTR"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 3
disqusShortname = "hpstrhugo"
relativeurls = true
[permalinks]
	posts = "/:section/:slug/"
	another = "/:section/:slug/"
[params]
	subtitle = "An elegant, responsive theme for Hugo"
	[params.image]
	  feature = "abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"

